version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: ".github/workflows" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    assignees:
      - yamatt
    labels:
      - dependabot
      - github-actions
