---
name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test Action
    env:
      REGION: fr-par
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      IMAGE_NAME: nginx
      CONTAINER_ID: ${{ secrets.CONTAINER_ID }}
    steps:
      - uses: actions/checkout@v6
      - name: Login to Scaleway Container Registry
        run: docker login $REGISTRY_URL --username nologin --password ${{ secrets.SCALEWAY_SECRET_KEY }}
      - name: Get latest Nginx image to run a web server
        run: docker pull ${{ env.IMAGE_NAME }}:latest
      - name: Correctly tag Nginx image
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
      - name: Push image to registry
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
      - uses: yamatt/scaleway-serverless-container-deploy-action@main
        with:
          container_id: ${{ env.CONTAINER_ID }}
          secret_key: ${{ secrets.SCALEWAY_SECRET_KEY }}
          registry_image_url: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
      - name: Check the image is using the latest version
        run: >
          [ $( \
            curl \
              --request GET \
              --header "X-Auth-Token: ${{ secrets.SCALEWAY_SECRET_KEY }}" \
              https://api.scaleway.com/containers/v1beta1/regions/${{ env.REGION }}/containers/${{ env.CONTAINER_ID }} | \
              jq -r .registry_image \
            ) = ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} \
          ]
